FROM golang:1.22.1 as builder

WORKDIR /app/
COPY go.mod go.mod
#COPY go.sum go.sum
#RUN go mod download
COPY server.go server.go
RUN CGO_ENABLED=0 go build -o /server
RUN chmod 777 /server

FROM scratch
COPY --from=builder /server /server
ENTRYPOINT ["/server"]
