FROM golang:1.22.1 as builder

WORKDIR /app/
COPY go.mod go.mod
#COPY go.sum go.sum
#RUN go mod download
COPY webserverclient.go webserverclient.go
RUN CGO_ENABLED=0 go build -o /client
RUN chmod 777 /client

FROM scratch
COPY --from=builder /client /client
ENTRYPOINT ["/client"]
